# name of database
db_name: "zabbix"
# hostname of the server hosting the database.
db_host: "localhost"
# port to use when connecting to database
db_port: 3306
# username for accessing database.
db_user: "zahapa"
# password for accessing the database.
db_password: 'verysecurepassword'
# port to recieve agent-check connections on.
port: 5555
# ip address for the agent-check to bind to.
bind: '0.0.0.0'
# The zabbix server node name. this is used for looking up the node status in the database.
zbx_node_name: "TRA-HYS-ZBXC201.hosting.fo" 
# interval for database greenlet to fetch status
monitor_interval: 5